### ISSUE TITLE
Add custom feed option to facebook app

### ISSUE THREAD

**Issue by perilandmishap** [charity-dynamics/charitydynamics-build-tool#17]

**Comment by eriksecker** [comment]
more info please?

**Comment by perilandmishap** [comment]
Yes please.

Uncovered some new requirements last minute, working with Charity to figure out what they really need here.

**Comment by perilandmishap** [comment]
In the UI this is a checkbox labeled "Include Custom 'Ask for Support' Message" and dropdown of links labeled "Custom Message Link".  Custom Message Link dropdown is only displayed if the box is checked.  These should be displayed on the Facebook App page.

**Comment by perilandmishap** [comment]
Added Custom Message to message profile:

The UI should allow users to enable/disable this message and change the link.  All other changes will be ignored by the backend.

stage: {
fbCustomMessageTemplate: {
channel: "FACEBOOK",
enabled: true,
key: "gtwo_choices_99",
link: {
id: "give_link"
},
},
