### ISSUE TITLE
Add news feed to mobile

### ISSUE THREAD

**Issue by perilandmishap** [charity-dynamics/charitydynamics-build-tool#18]

**Comment by perilandmishap** [comment]
Users may enter a Facebook page id and/or Twitter screen name to populate news feeds in the Mobile application.  These fields are in ProgramConfig and should be displayed on the Mobile App section.

{
rssFb: "fbPageId",
rssTwitter: "twitterScreenName"
}

**Comment by eriksecker** [comment]
I'm planning to add these to Mobile App > Settings (screenshot attached) with the other program config fields.  Does this make sense from a UX perspective?  Also, what should the labels be?
![screen shot 2015-08-17 at 5 20 07 pm](https://cloud.githubusercontent.com/assets/12503398/9316664/5c386e36-4504-11e5-8e2a-633bac09dce1.png)

**Comment by perilandmishap** [comment]
Yes, I think putting them there is good.  Lets go with a subheading of
"Event News" and "Twitter Screen Name" / "Facebook Feed Id"

Thanks!
