### ISSUE TITLE
Restore Issues

### ISSUE THREAD

**Issue by eriksecker** [charity-dynamics/charitydynamics-build-tool#19]
I've got Push History wired to call a restore, but I'm getting the following error:
"503 Service Unavailable 30.04s"
It seems like a timeout, but I don't see any data changes in the system after I do a refresh a few minutes later either -- though perhaps it's possible I'm not fully understanding what the data is expected to look like after a restore.

**Comment by perilandmishap** [comment]
This is a timeout.  The restore operation restores the Prod database back to the state it was in when the snapshot was taken.  No changes are made to the Stage config.

Made the inserts multithreaded.
time before threads: 128,204ms
time after threads: 52,821ms

Which is great but our timeout is 30,000ms...

I've updated the code so it doesn't wait for the restore threads to return so client development can continue.  The 30 sec timeout is enforced by heroku, they suggest using Server-Sent Events to work around this problem.  

The two tables that take a long time are feeds and strings, both have a < 500 entries, a 3 part index, and use ON UPDATE CURRENT_TIMESTAMP.
