### ISSUE TITLE
Add/Delete message from Ask list

### ISSUE THREAD

**Issue by perilandmishap** [charity-dynamics/charitydynamics-build-tool#31]
Ability to add/remove a message from Scheduled Messages, Get Donations, Ask for Support sections

**Comment by perilandmishap** [comment]
Creating new Ask is working. Workflow is as follows:

1. Client calls API to create new ask
name is the only required field.
type and schedule are optional.

http://localhost:8080/api/program/proteatest/createAsk/MOBILE
{
  "schedule": {
    "duration": "3",
    "before": "true",
    "type": "COUNTDOWN"
  },
  "name": "This is my new Ask",
  "type": "0"
}

2. The server responds with the new ask we created, including the id needed to update it, and all the messages for that ask.  These messages are created in a disabled state:
{
  "data": {
    "_id": "gtwo_choices_8|email_8|twitter_choices_8|sms_choices_8|linkedin_choices_8",
    "feeds": {
      "TWITTER": {
        "channel": "TWITTER",
        "enabled": false,
        "key": "twitter_choices_8"
      },
      "SMS": {
        "channel": "SMS",
        "enabled": false,
        "key": "sms_choices_8"
      },
      "LINKEDIN": {
        "channel": "LINKEDIN",
        "enabled": false,
        "key": "linkedin_choices_8"
      },
      "FACEBOOK": {
        "channel": "FACEBOOK",
        "enabled": false,
        "key": "gtwo_choices_8"
      },
      "EMAIL": {
        "channel": "EMAIL",
        "enabled": false,
        "key": "email_8"
      }
    },
    "name": "This is my new Ask 2",
    "type": 0
  },
  "success": true
}

3.  The client then uses the resulting message keys to update and enable each message using:
POST /program/{programCode}/updateMessage/{scope}

**Comment by perilandmishap** [comment]
Deleting an ask works using 
POST /program/{programCode}/updateAsk/{scope}
Only the _id and deleteMe flag are required.
example:
{
"_id": "gtwo_choices_9|email_9|twitter_choices_9|sms_choices_9|linkedin_choices_9",
"deleteMe": true                 
}

**Comment by perilandmishap** [comment]
On Review or Push the server will cycle through all the ask arrays doing the following:

- Check to see if the ask already exists, 
 - If it does not create one using the id provided (and also the order provided)
 - If it does call the update routine
   - the update routine checks for the deleteMe flag and if it is set deletes the message

If doing a review then the change set is collected but no changes are made to the database, change sets from review and push behavior are the same as those from each individual call.

**Comment by eriksecker** [comment]
this is complete and checked in
