### ISSUE TITLE
Validation - Field Validation

### ISSUE THREAD

**Issue by perilandmishap** [charity-dynamics/charitydynamics-build-tool#32]
Talked to Kathy about validation requirements.  There are two kinds: field validation required to save a fieldset, and validation that is required before doing a push (errors for this kind of validation should be displayed in the status boxes on the Program page and on the Review page. This ticket has details on Field Validation.

- [x] Application Title is required and must not be blank
- [x] A platform type must be selected (platform.platformName)
- [x] mobilePrimaryColor, mobileSecondaryColor, mobileThermoColor must match the regex for an html color

- [x] For all messages except mSolicitations, Title (if displayed) and Content are required and must not be blank.  Title and Content may be blank for the Get Donations messages.
- [x] For scheduledMessages, fbSolicitations, and mSolicitations Ask.name is required.
- [x] Messages with channel SMS or Twitter should be no more than 144 characters

- [x] All fields in each badge section are required and should not be blank
- [x] badge color must match regex for html color
- [x] badge size must be a positive integer

**Comment by eriksecker** [comment]
We have the UI set to not display ask.name for fbSolicitations, though above the instructions are to make it required.  Since there wasn't data being sent from the API on these, I'm guessing the instructions above are incorrect, but let me know.

**Comment by perilandmishap** [comment]
Yes, those instructions are incorrect.  Ask name is required for mSolicitations and for scheduled messages.  It is not required for fbSolicitations, sorry.

Bonus points, with mSolicitations Ask.name also must be unique and very strange things will happen if this rule is violated.  I was going to take care of that on the backend, but some previously unknown differences in their production environment have popped up, so I'm chasing that down instead.. Could you squeeze this in too?

**Comment by eriksecker** [comment]
Created a new ticket #38 for unique ask.names in mSolicitations.  I'll do my best to squeeze it in.
