### ISSUE TITLE
Facebook -> Ask For Support titles

### ISSUE THREAD

**Issue by perilandmishap** [charity-dynamics/charitydynamics-build-tool#6]
Titles are not displaying and hitting save after editing triggers no action.

**Comment by eriksecker** [comment]
The save functionality is in place.  I've updated one of the ask titles and after save, I am receiving the new value and the display is working correctly.  The rest of the empty titles seem to be a result of them coming down from the server as "name": ""

**Comment by perilandmishap** [comment]
Did some digging, this looks like a requirements issue.  Their facebook app doesn't display a title for these feeds - instead it truncates the message content and uses that.  Some programs are missing the entry in strings for the ask title, so my update query has no effect.

Since filling out the title will have no effect let's not display this field to users.  Please remove the Title field from Ask For Support messages under Facebook.  The audience field should continue to be displayed.
